Capture_cnt: 3
Capture.fps: 5
Capture.topic: "multi/image"
Capture.percent: 0.0001
# Capture.percent: 1
Capture0.VideoPath: "/home/wen/SLAM/Datasets/data/left/*.png"
Capture0.topic: "left/image"
# Capture1.VideoPath: "/home/wen/HardDisk/VisDrone/SOT/VisDrone2018-SOT-test-dev/sequences/uav0000021_00000_s.mp4"
Capture1.VideoPath: "/home/wen/SLAM/Datasets/data/right/*.png"
Capture1.topic: "right/image"

Capture2.VideoPath: "/home/wen/SLAM/Datasets/data/wide/*.png"
Capture2.topic: "wide/image"