model_path: /home/wen/Desktop/Production_1/Data/root.osgb
mappoint_size: 5.
camera_width: 1
is_show_model: true
window_x: 0
window_y: 0
window_width: 1200
window_height: 1600
gt_traj: /home/wen/SLAM/MCVSLAM/data/trajectory_ori.txt
follow_tf: 0 0 200